# About Us {#about_us}

## Who we are

We are [Dr Ashley Robertson](https://www.gla.ac.uk/schools/psychologyneuroscience/staff/ashleyrobertson/){target="_blank"} and [Dr Holly Neill](https://www.gla.ac.uk/schools/psychologyneuroscience/staff/hollyscott/){target="_blank"} and are both Lecturers in Psychology within the School of Psychology & Neuroscience at the University of Glasgow.  

We both run group dissertation supervision (although in different ways!) and we developed this joint resource to help others who want to run group dissertation supervision.  Through this book, we hope to provide some ideas of how you could incorporate group supervision in a way that works for you. You may or may not currently supervise in groups: either way, we will provide some ideas of activities you might want to try in group supervision, as well as make some suggestions about how you might want to structure group supervision.  

Although we come from a background of Psychology, and there will be some references or literature referring to supervision in Psychology, we have kept this resource general and open, so that it could apply to dissertation supervision across many disciplines.

## How to use the resource 

This resource can be used however you want! Please feel free to use the information contained within it, to adapt it for your own uses, or to pass on to others.  

This book draws on what we’ve both learned about group supervision and provides some resources for you to try out.  


## Further information

If you have any questions at all, or would like us to deliver a workshop or talk in your department on Group Supervision for Dissertations please feel free to get in touch with [Ashley](mailto:ashley.robertson@glasgow.ac.uk){target="_blank"} and [Holly](mailto:holly.neill@glasgow.ac.uk){target="_blank"}

It can be hard to evidence impact of resources like this, as there is no way to track if people are accessing it and using anything from it. If you find any part of this resource useful or end up using something from it in your own supervision, we would be **hugely grateful** to you for taking the time to let us know. We've set up a [Microsoft Form](https://forms.office.com/e/st5k1td5YQ) which can be used to give some feedback. 
