# Benefits (and challenges!) of Group Supervision {#benefits}

One of the biggest assumptions that we have come across is that Group Dissertation Supervision is only possible if all students work on the same project (e.g. looking at different variables). 

However, this is not a requirement (and is not how we run our supervision!). In this chapter, we will cover different models to group supervision (including what we do), and why it can be beneficial to supervise dissertation students as a group, even if students are working on completely different projects. 

## Different models of Group Supervision 

There are many different models of dissertation and, indeed, many different models of supervising dissertation students as a group. 

[Creaven et al. (2023)](https://doi.org/10.1525/collabra.90216){target="_blank"} detail different models of undergraduate dissertation supervision in Psychology in their paper. 

Thinking specifically about group supervision, these include:

- Collective Academic Supervision
  - Students meet only as a group and undertake independent (but similar) projects, supervised by the same supervisor
  - Example: [Dautel (2020)](https://doi.org/10.53841/bpsptr.2020.26.1.18){target="_blank"}
- Consortium model
  - Consists of multiple groups of students across different Universities collaborating on one protocol and supervised by supervisor in their University
  - Example: [Button et al. (2020)](https://doi.org/10.1177/1475725719857659){target="_blank"} 
- Apprentice-Based Senior Thesis
  - Students collaborate together in small groups on one protocol; supervised by a single supervisor
  - Example: [Mickey-Steinmetz & Reid (2019)](https://doi.org/10.3389/fpsyg.2019.00196){target="_blank"} 
- Laddered Model
  - Students are separated into three-person teams, with each team consisting of three students with differing levels of expertise (one experienced, one mid-level and one new to the group)
  - Example: [Detweiler-Bedell & Detweiler-Bedell (2019)](https://doi.org/10.3389/fpsyg.2019.00133){target="_blank"}
- "Cluster" projects 
  - Two members of staff collaborate to supervise students (in groups as well as individually) on projects sharing a) a topic, b) a research question, c) methods or d) type of data analysis. 
  - Example: [Freeman et al. (2020)](https://doi.org/10.53841/bpsptr.2020.26.1.39){target="_blank"}

There will be other models of supervision used, especially across different disciplines. 

### Our models of supervision

Each of us supervises both Undergraduate and Postgraduate Taught students. We use slightly different models of supervision to each other, although both are closest to the 'Collective Academic Supervision' model described by Creaven et al. (2023). 

To provide some context, our Undergraduate supervision is for final year students who are on-campus, whereas our PGT supervision is for students who are completing their dissertation through Online Distance Learning (and are therefore based all over the world).

In this book, we will mainly discuss how we supervise for final year undergraduate students, as we have found it difficult to schedule group supervision for Online Distance Learning students due to working commitments and differing time zones. Saying this, our supervision approaches are not specific to undergraduate students and apply equally well to postgraduates. 

::: {.callout-tip icon=false}

## Ashley's supervision model

Ashley holds a mixture of group and individual supervision, switching between the two on a weekly basis:

- Fortnightly group supervision (e.g. Weeks 1, 3, 5 and so on) 
  - Each supervision is 'themed', with focus on skill development and covering challenges that are consistent across all projects
  - Resources are passed on to students: [full breakdown of each session across two semesters can be found here](https://ashleyerobertson.github.io/group_supervision/){target="_blank"}
  - Each session scheduled for around 1 hour, although the final session is longer
- Individual supervision (e.g. Weeks 2, 4, 6 and so on)
  - An example of a ['Touching base' session](#supervision_types){target="_blank"}
  - Individual sessions are dedicated time for students to ask questions, discuss project-specific challenges/concerns and identify priorities for progress
  - Actions noted for future sessions
  - Deadlines set using the 'joint deadlines document' (see [Chapter 3](#set_up){target="_blank"})

:::

::: {.callout-tip icon=false}

## Holly's supervision model

Holly holds group supervision sessions on a weekly basis. She splits this between two different types of group supervision sessions:

- 'Milestone' group sessions
  - Around three milestone sessions are held per semester, each consisting of collaborative activities
  - With larger groups (e.g. six or more), these are scheduled for around 1.5 hours each
  - Students are asked to complete activities in advance and during each milestone session
  - Examples of activities covered in milestone sessions are in [Chapter 5](#supervision_examples){target="_blank"}
- Regular group supervision (or ['Touching Base' session](#supervision_types){target="_blank"})
  - Held on a weekly basis, in the weeks that there is no milestone session
  - Opportunity to catch up on progress, ask questions and plan progress
  - Actions noted for future sessions

:::

 
## Why Supervise Dissertations as a Group? 

Historically, dissertations have been supervised one-on-one, in an 'expert' and 'apprentice' model [(McCallin & Nayar, 2012)](https://www.tandfonline.com/doi/full/10.1080/13562517.2011.590979){target="_blank"}. Group supervision can offer both peer and supervisor support, and can deepen learning by exposing students to varied theoretical and methodological perspectives [(Nordentoft et al., 2013)](https://www.jstor.org/stable/23473513){target="_blank"}. Students can benefit from hearing varied points of view and being exposed to different research designs and topics. It can also be an efficient way to supervise (as there is no need to repeat information multiple times) and allows students to learn from the questions that they never thought to ask. 


### Feedback from students  

Here is just some of the feedback that students who have been supervised through group supervision in our School have left about their experiences. 

::: {.callout-tip icon=false}

## Feedback from students

Group meetings were "motivating", "inspiring" and "comforting"

"Hearing other people’s ideas and perspectives was so helpful"

"It was so lovely to get to feel a part of the community"

"Excellent, would honestly recommend this format"

:::

In general, students in our School report enjoying group supervision as it helps them to feel less isolated and they learn from their peers as well as their supervisor. It can also be an enjoyable experience! 


### Benefits for students

In our experience, group supervision has been beneficial for the students that we have supervised:

- Student wellbeing
  - In our School often the students won't know their peers within their dissertation group. Working together can give valuable alternative perspectives and help students to connect with each other. This can help to facilitate feelings of connectedness among the cohort. 
- Support each other
  - Peer support can be a useful result of students becoming familiar with each other through group supervision. This might be led by supervisors (e.g. as in Holly's examples where students give feedback to each other) or can be organised by students themselves (e.g. Ashley's students met as a group to practice setting up an interview together). 
- Gain experience of how teams work
  - Working together in a group setting can provide students with an opportunity to work on a longer project with others. It can expose students to diverse perspectives, to develop an understanding of different roles within a team and to learn to balance both individual and group responsibilities.
- Develop transferable skills in collaboration
  - Working as part of a group enables students to develop key skills that are important for employers, such as communication skills, critical thinking, time management and negotiation.

### Benefits for staff 

There are also key benefits for staff in including group sessions within your supervision:

- Manage workload efficiently
  - Seeing students as a group, either alongside individual sessions or solely as a group, can reduce required contact time, easing pinch points in workload. 
- Group together common queries and concerns
  - There are often similar questions and concerns, or information that is common to all projects. Supervising as a group can allow you to maintain a consistent message about expectations, and reduce time spent sharing the same information.
- Enjoy the group dynamic! 
  - It is often a pleasant experience to see students develop and grow over the course of their dissertation, and this is no different with group supervision. It is enjoyable to see students supporting and learning from each other throughout the year. 

## Challenges of Group Superivison

It is also important to note that Group Supervision is not perfect and without any issues! [Nordentoft et al. (2013)](https://www.jstor.org/stable/23473513){target="_blank"} developed the Collective Academic Supervision model. In a subsequent paper, the same team identified three main challenges with supervising students collectively [(Wichman-Hansen et al., 2015)](https://link.springer.com/article/10.1007/s10734-014-9821-2){target="_blank"}:

- supporting diverse groups of students to contribute equally
- striking an optimal balance between passing on information and involving students in learning
- determining how to support the growth of students' evaluative and analytical skills

In our experience, some of these can be addressed by not requiring that students work together on shared projects (e.g. social loafing is less of an issue in individual projects, even if students are supervised as a group), and others can be addressed by planning interactive activities for the sessions that are focused on skill development. [Wichman-Hansen et al., (2015)](https://link.springer.com/article/10.1007/s10734-014-9821-2){target="_blank"} suggest that setting expectations are very important, although future research is needed in terms of supervisors' experiences of group supervision, as well as better understanding different ways of interacting in these contexts. 

Sometimes, one concern that staff have is that some groups are quieter than others, and that group supervision can feel a bit 'flat' or require the supervisor to constantly facilitate discussion. This is one of the reasons that Ashley has [a clear theme and structure for each group session](https://ashleyerobertson.github.io/group_supervision/){target="_blank"}. It can often take a little time for quieter groups to warm up, especially when there are no pre-established relationships. Try not to worry if groups are a little quiet at the start - this usually eases up over time and formerly quiet groups will often suddenly have lots to discuss after a few weeks/months.
