# Different types of Supervision Sessions {#supervision_types}

We both split our supervision into two types of sessions: unstructured or ‘touching base’ sessions and structured sessions.  

Although these look different for both of us, our supervision contains both types. 

 
## ‘Touching Base’ Sessions 

These tend to be sessions where students might bring along their questions and update you on their progress. There are many different options! 

Ashley has these as individual sessions, held fortnightly whereas Holly has them as weekly group sessions (in the weeks where she does not hold a structured session).  

Other staff members in our School schedule drop-in sessions or have specific office hours for students. Others have these based on projects, putting students into pairs or smaller groups.  

### Things you might want to cover in a ‘Touching Base’ session 

**[ADD A LITTLE BIT OF FRAMING HERE FOR THIS]**

- How is progress going?  
- How is the student finding their project?
- Do students have any concerns?
    - Ethics 
    - Recruitment & Data collection 
    - Analysis 
    - Writing 
- What questions does the student have? 
- What is the student hoping to achieve in the next week/fortnight/by the next session? 
- Record-keeping (e.g. outcomes/actions from the supervision session) 

## Structured Sessions 

In the next Chapter, we will share some worked examples of the types of activities we use in our structured sessions. For each, we’ll share example text of communicating the activity rationale to students, an accompanying resource for students, and some of our tips for supervisors on how to run each group session. Feel free to use any of these as they are, adapt them to the needs of your students, or perhaps the examples will inspire some of your own new ideas! 

Before we made this joint resource, Ashley also developed a separate book detailing each structured session that she runs, with an overview of what’s covered for each one, along with links to resources. If you would like to take a bit of a ‘deep dive’ into how these sessions might be structured, you are very welcome to access this too. You can find this in [Structured Supervision Sessions for Group Supervision](https://ashleyerobertson.github.io/group_supervision/){target="_blank"}.  
