---
title: "Examples of Group Supervision Sessions"
---

## Lightning Talks 

*Written by: Dr Holly Scott* 

Lightning talks are short-form presentations (typically 5 minutes maximum) that challenge presenters to summarise their ideas very concisely. The short duration makes Lightning Talks perfect for incorporating into group sessions, and this can be done at any stage in the dissertation. Here is an example of supporting students to clarify their dissertation plans by giving a Proposal Lightning Talk early in the process. 

### Rationale to share with students 

Here is how I explain the rationale behind this activity to my students: 

::: {.callout-note appearance="simple" icon=false}

## Example Rationale for Lightning Talks

As discussed, in next week's meeting we will have short (5 min max) "Lightning Talks" on everyone's proposals. This format is now quite common at conferences, as a way to concisely convey the key take-away messages of a study, allowing interested audience members to discuss more details with you afterwards. 

Some of the benefits of you doing this for your proposal are:  

- You clarify your key arguments/decisions by having to communicate them concisely 
- You can get informal feedback from the group before finalising your proposal document 
- You practice skills in presenting that you will use in your course and in future work settings 
- You get to see how others in the group are approaching issues that could inform your thinking/approach to your own study 

I have shared a template PowerPoint. It's 5 slides and I would challenge you to be as concise as you can. Once you have prepared your proposal document, you can pick out the key points and add them to the slides. Remember that this is for informal feedback from the group - we're not expecting you to get everything right first time and we will be a super supportive and encouraging audience! 

:::


### Accompanying resource 

This activity has an accompanying PowerPoint template [link] - feel free to use or adapt this. Depending on their course, this may be one of the first presentations that students have given during their time at university, and they are only at the start of their dissertation. Therefore, I find it helpful to provide this scaffolding to help ease any nerves. 

### Running the group meeting 

In terms of the practicalities of running this group meeting, I ask students to share their slides in advance (for example, in a shared Teams folder) to allow a quick set up and smooth running on the day. I explain to students that – similar to many conferences – I will give them a 1-minute warning and then a “time up” signal. 

We have time for questions after each Lightning Talk. It might be the first time that students are audience members for this type of academic talk, so it can be helpful to provide some guidance at the start of the session on what types of questions they might want to ask. Being mindful that some students can feel nervous about this type of talk, I offer them the option to stay standing up for questions or to rejoin the group for a more informal discussion around the table if they prefer. 

I like to aim for a supportive and encouraging tone in this session. I emphasis that this is about getting some practice and helpful feedback, not about getting everything perfect. To help create a positive atmosphere, I like to light-heartedly challenge my students to “win” at being the most supportive audience: lots of smiling and nodding! 

It can be good to finish this session by inviting students to crowdsource their tips for giving this type of talk, based on what they learned from their experience as a presenter and an audience member. Afterwards, this can be a great stage to encourage students to reflect on their skills development: we provide some guidance on how to support this in Chapter 6 [link]. 


## Presenting an Outline for a written section

*Written by: Dr Holly Scott*

One area that I wanted to support my students to improve was developing a cohesive and persuasive overall argument in the Introduction as to why their research question merits investigation. To support this, I invite students to produce a bullet point outline of their Introduction plan, focusing on convincing the reader of their study rationale. In a structured group meeting, students then talk the group through their outline. This offers the opportunity to clarify their ideas by concisely articulating them to the group, and to receive constructure feedback on areas for enhancement from their peers. For example, as naive readers/listeners, the group may highlight a gap in the logical progression of an overall narrative. 

While this example focuses on the Introduction and rationale, the same approach can be used for any section. For example, it may be useful for constructing a Discussion plan and targeting any areas you feel that students have found trickier, such as supporting their study limitations with evidence. 

### Rationale to share with students 

Here is an example of explaining the rationale behind this activity to your students: 

::: {.callout-note appearance="simple" icon=false}

## Example Rationale for Outline of a Written Section

It’s time to start planning for drafting the Introduction. For next week, I’d like you to prepare a bullet point outline of your Introduction section, where each bullet point briefly summarises one key step in your overall argument to convince your reader why this study should be done. You will share this outline and, at our meeting, talk the group through the outline for some feedback. Some of the benefits of doing this task are: 

You will organise your thoughts and start to build a coherent narrative for your Introduction draft that covers all key arguments. 

You will gain feedback from me and your peers on the logical progression of your outline, including constructive suggestions for improvements. 

You will be able to use your finished outline to break down the task of drafting an Introduction into manageable chunks. 

You will practice clear and confident verbal communication by articulating your ideas to the group, which is an important skill for the future. 

I have shared an example bullet point outline for the Introduction of one of my papers. This is simply one example of how this might look. Don't feel that yours has to follow a similar structure: this is just an example of focusing on the logical progression of key arguments. 

:::

### Accompanying resource 

I share this [one-page resource with students on outlining an Introduction argument](https://gla-my.sharepoint.com/:w:/g/personal/holly_scott_glasgow_ac_uk/EcoHr69hY6tLrK_krvx1ry0BqY64ST7FUjgnPx6HieDiPw?e=Zsdra8). Following the group meeting, I also share an [Introduction progress tracker](https://gla-my.sharepoint.com/:x:/g/personal/holly_scott_glasgow_ac_uk/EeFbRP3I92xBgAQNs3qJ-KwBvaAAoE1MhwNu7_yMYnAU6A?e=ssVGTy), where they can insert each key argument/paragraph and log their progress on e.g. gathering literature to support it, making notes, drafting and redrafting. Students have found this helpful to get over the daunting blank page when they begin drafting, as they can break the task down into manageable chunks. 

As with all the resources in this book, you are welcome to use these as they are, adapt them, or take them as inspiration for creating your own. 

### Running the group meeting 

On a practical note, it is helpful if students share their written outlines in advance: for example, I create an “Introduction Outlines” tab on our shared OneNote with pages named for each student. 

In the structured group meeting, each student in turn talks through their proposed outline, while the rest of the group listens out for whether the content, ordering and linking make sense to someone reading/listening for the first time. This forms the basis for useful wider group discussions on how to structure an Introduction, how to make links between ideas etc. 

This is also a useful session to take some time to discuss how different students approach writing, including what they have found helpful or tricky in the past. This creates an opportunity to crowdsource some top tips, and for students to gain comfort knowing that they are not alone in finding some aspect of writing challenging. This can open nicely into a wider group discussion around issues raised, e.g. overcoming perfectionism.  

## Peer Review

*Written by: Dr. Holly Scott*

Peer review offers students a useful opportunity to view written work through the lens of a marker, engaging with the Intended Learning Outcomes of the assessment to identify strengths and recommend areas for improvement. Reviewing a peer’s draft can encourage students to think critically about aspects of writing that they want to emulate or avoid in their own work, and those who engage more critically have been shown to go on to earn higher grades [(Yalch et al., 2019)](https://journals.sagepub.com/doi/10.1177/1475725719835070){target="_blank"}.  

Dissertation students can engage in peer review of all sorts of materials: not only drafts, as in this example, but also proposals, ethics applications, materials etc. Peer feedback can be written and/or verbal: in this example, students share written feedback on a draft before a group meeting where this forms the basis for group discussion. 

### Rationale to share with students 

Here is an example of explaining the rationale behind this activity to your students: 

::: {.callout-note appearance="simple" icon=false}

## Example Rationale for Peer Review

Congratulations on completing your Introduction drafts, what a great milestone! As discussed, we’re going to use this as an opportunity for some peer review. The advantage of engaging in this peer review task include: 

- You will benefit from added feedback on your draft, not just from me but also from a peer  
- The evidence shows that the process of reviewing others' written work helps you to then improve your own
- You will build experience of how teams work together to produce output (not just in research but all sorts of workplaces) 
- You will also develop important transferable skills in giving constructive feedback (both written and verbal) 

I have shared a peer review form with some questions for you to reflect on as you read your peer’s work this week. Remember that this is an opportunity to support each other by identifying what is already working well, what could be improved and importantly how it could be improved. Next week we will have a chance to discuss our feedback and crowdsource ideas to help with any common tricky areas. 

:::

In this message to students, I will also list who will be reviewing whose work. You can consider what will support the most useful feedback (for example, grouping together similar methods) as well as avoiding any pitfalls (such as not grouping students together who are working closely on shared pair or group projects, to prevent unintentional plagiarism). 

### Accompanying resource 

Here is an example of a peer review form for Introduction drafts [link]. It is helpful to provide some structure and prompts like these for students to reflect on as they read and review. Feel free to adapt this to suit your own Intended Learning Outcomes or perhaps target common problematic areas of drafts that you have seen repeatedly. 


### Running the group meeting 

In terms of set up, I create a shared space (e.g. a Teams folder) where students upload their written feedback ahead of the meeting (say, 24 hours before). So far, I have always shared my own feedback comments for each student here as well, facilitating transparency. However, depending on your group of students each year, if there are any issues then you may consider it more appropriate to send feedback individually. 

As with any interactive session, I like to set a supportive tone and start by reminding the group that all discussion should be encouraging and constructive. I have always been genuinely impressed by the quality of written feedback in my students’ peer reviews, with a consistent encouraging tone and concrete, constructive suggestions for enhancement. This in turn forms the basis for a very productive and supportive group session: for example, it can be useful for students to share experiences of what they found trickier in writing their drafts, to know that they are not alone. 

In practice, during this meeting, I facilitate a group discussion focused on each student’s draft in turn, initially based on input from me and their peer reviewer (on what is working well and what areas they can focus on refining), then opening into a broader discussion about how some of these improvements can be achieved in any strong discussion (involving all group members). Where relevant, it can be encouraging to point out strong aspects of students’ work that are a good example: for instance, if one student has found it difficult to create logical links between paragraphs and another student’s work has good examples of achieving this. 


## Evaluation of a Discussion section

*Written by Dr Ashley Robertson (jointly developed with [Dr. Wil Toivo](https://www.gla.ac.uk/schools/psychologyneuroscience/staff/tarutoivo/){target="_blank"}*

In my experience, one of the areas that students find quite tricky to write for their dissertation is the Discussion section. It is also the only section that students do not receive feedback on from supervisors (in our School, students get feedback on Introduction, Methods and Results only). It can also be quite difficult for students to demonstrate more complex evaluation skills.  

To support this, my colleague and I developed some materials to support students when writing a Discussion section, highlighting key issues that we often see. These were designed for use in labs for our research methods course, but we have since also used them in our group dissertation meetings. As we had had instances of students copying examples and only changing a few words, we chose a topic that was very different (**postgraduate students' confidence in surviving the zombie apocalypse**), in order to encourage generalisation of the skills learned. To support this, we used GenAI to provide the basis for the ‘not so good’ examples.

### Rationale to share with students 

Here is an example of explaining the rationale behind this activity to your students: 

::: {.callout-note appearance="simple" icon=false}

## Example Rationale for Evaluation of the Discussion

In the next session, we are going to do some activities to support you when you come to writing your Discussion. I have provided three different ‘not so good examples’ from a Discussion section: what points can you identify? In the group meeting, we will discuss what you found. We will then look at some better (not perfect!) examples and discuss these too. Finally, we will identify some actions that you can take to support the writing of your Discussion section. 

Some of the benefits of doing this task are: 

- You will be able to identify common mistakes that are made when writing Discussion sections 
- You will benefit from the wider discussion of the group around what staff look for and do not look for in a Discussion section 
- You will identify clear and actionable points that you can apply to your own writing of the Discussion section 
- You will practice discussing your ideas with your peers and staff, which is an important skill for the future 

I have shared three ‘not so good’ excerpts from a Discussion section. For each, identify some issues for each. We will then see what everyone in the group identified once we meet.  

:::

### Accompanying resource 

Here is a [copy of the excerpts we use for the Discussion evaluation activity](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EZnXNcupuYpPvtTctLIQHP4BPpKRakEyzQjnrhInkfOSHg?e=Sk2bCi). 

There are three particular aspects of Discussion sections that we are looking at in this activity:  

- Excerpt 1: Linking findings to the evidence base 
- Excerpt 2: Limitations 
- Excerpt 3: Implications 

We have developed some [notes for staff](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/ERJe-GFNvg9GlKjPGDFmjL0BftYJBXBcvzw8U9ofZ1XH-Q?e=dnLOfb) running this activity, with some of the strengths/limitations for each of the excerpts. 

Please feel free to adapt the activities or the notes in a way that works for you in your own supervision. 

### Running the group meeting 

To set this up, I create a thread on Teams (I have a shared Teams channel just for my dissertation students and me) and post the excerpts along with the rationale. This allows students time to prepare if they prefer. The excerpts are very short, so if students don’t have time to read through them before the meeting, this is not a problem as I can give everyone a few minutes to do it there and then. I have included the excerpts as well as some notes for staff for this activity under ‘Resources’ above. 

I usually have printed copies of each of the excerpts (both ‘not so good’ and ‘better’), so we can see them. We go through the ‘not so good’ (1A, 2A and 3A) together and I facilitate a discussion on this. Once these issues have been identified, I show the students the ‘better’ examples (1B, 2B and 3B) one at a time. For each one, I give them a minute to read it and then we have a discussion about what was better about this example. There may also be some problems they identify too, as these are not designed to be perfect.  

Then, I ask each student to identify one thing that they’ve learned from the session to incorporate into their own Discussion section. I then ask them to write this down and commit to this as an action when they come to write or edit their Discussion.  


## Conference presentation 
*Written by Dr Ashley Robertson*

It is important for students to develop skills in presenting. In our School, we hold a conference for students one week after they have submitted their dissertation, in order to help support these skills.

Students have the opportunity to present in one of the following ways: 

- Scientific presentation 
- Lightning talk
- Bright Club/Pint of Science talks
- Panel discussion
- Written Science Communication piece 

The talks and discussions are presented live in the conference, and the written contributions collated together and sent out. Most students choose to present live at the conference.

Although this is a very supportive experience, students can find presenting a bit daunting. To help, I hold a practice session for those students working with me, to provide them with an opportunity to practice their talk before the conference itself. It also enables those presenting at the British Psychological Society Scottish Branch Undergraduate conference to have an additional opportunity to practice speaking in front of others.

### Rationale to share with students 

::: {.callout-note appearance="simple" icon=false}

## Example Rationale for Conference presentation

In our final group session together, we are going to hold a practice session for your contribution to the Level 4 undergraduate conference on [DATE]. This will be both a celebration for completing your dissertations as well as a practice conference presentation.

The advantages of taking part in this conference practice session include:

- Having an opportunity to practice in a safe space. If doing a talk, you can run through this in front of the group. If you have chosen a debate, I can ask you some practice questions. If you have chosen a written contribution, you can outline what you are planning to cover.
- You will have the opportunity to practice responding to questions from the audience, which will help prepare you for the conference
- You will receive feedback from me (and hopefully each other!) on your talk/debate/outline, helping to refine your contribution
- Presenting your work is a highly sought-after skill that employers value
- It gives us the opportunity to come together after all your hard work on the dissertation and celebrate your achievement together!

In preparation, please let me know in advance which type of talk or other contribution you are doing in the conference. We will have a slightly longer session than usual, to make sure that we have plenty of time and aren't rushed. 

:::

### Accompanying resource 

In a previous group session, I will have shared some of my [*tips on presenting*](ADD LINK), as well as some suggestions from [*add uni here*](ADD LINK). I will reshare these with the students in advance of the group session. 

### Running the group meeting 


