# Finding what works for you {#what_works}

We wanted to end the book by thinking about how to find what works for you. We hope that this book gives you some ideas for trying out group supervision in some way, although we aren't suggesting that you do exactly the same as us. You might choose to have only group supervision from now on, or you may decide it's not for you at all. Others might choose to have some sort of combination of group and individual. 

Something to be aware of is that group supervision might not work perfectly first time - it can involve a bit of trial and error. Both of our supervision models have evolved over time and we reflect on what works and what doesn't, tweaking what we do each year. It can be a challenging (and rewarding) process. Sometimes, group supervision can depend on each specific group of students - some things might work with one group but not with another. You might also have to make exceptions for particular students at times. Our main suggestion would be to be responsive to how supervision feels, and don't feel that you can't make changes at any point. 

We have included some concrete suggestions for sessions in [Chapter 5](#supervision_examples). Please feel free to use as much or little of these as you wish, and to adapt them or pass them on to others. These are designed to give some ideas for what you could do in group supervision, but is not meant to be prescriptive. There are likely to also be examples of excellent practice within your own University and Department/School. 

If you are struggling to get started, it can sometimes be helpful to think about one thing that you notice that would be good to work on with students (e.g. could the rationale of their project be clearer, or evaluation?). Designing some sort of activity around that key aspect of their work may then be a good place to start off! 

We would love to hear from you if you end up using any of the book in your practice, would like to discuss things with us further or have some suggestions for how we could adapt the book in the future!

If you would like to get in contact with us, feel free to email us:  [Ashley](mailto:ashley.robertson@glasgow.ac.uk){target="_blank"} and [Holly](mailto:holly.neill@glasgow.ac.uk){target="_blank"}

As mentioned in Chapter 1, we've set up a [Microsoft Form](https://forms.office.com/e/st5k1td5YQ) which can be used to give some feedback if you've used any of the resource. 
