# Overview {.unnumbered}

Welcome to our book on supervising dissertation projects in groups. Please feel free to use whatever you find useful, to pass on to others, and to adapt these resources to suit your own supervision style. 

You can navigate to each of the chapters using the bar on the left hand side, or using the links below. Within each chapter, a breakdown of the main sections will be provided on the right hand side. 

We have structured the book as follows:

**Main Chapters**

- Chapter 1: [About Us](#about_us)
- Chapter 2: [Benefits (and challenges!) of Group Supervision](#benefits)
- Chapter 3: [Getting Set up for the Year Ahead](#set_up)
- Chapter 4: [Different Types of Group Supervision Sessions](#supervision_types)
- Chapter 5: [Examples of Group Supervision Sessions](#supervision_examples)
- Chapter 6: [Employability and Transferable Skills](#employability)
- Chapter 7: [Finding What Works for You](#what_works)

**Appendices**

We include two appendices in this book. Appendix A is a document to support setting expectations and is discussed in [Chapter 3](#set_up). Appendix B is a list of resources collated by Ashley that may be useful when supervising a group.

- Appendix A: [Setting Expectations](#appendix_a)
- Appendix B: [List of Resources](#appendix_b)


### Partner Book

There is an accompanying group supervision resource, developed by Ashley, on [Structured Sessions in Group Supervision](https://ashleyerobertson.github.io/group_supervision/){target="_blank"}
